### ISSUE TITLE
Account Data API - Transaction Codes

### ISSUE THREAD

**Issue by cdubalaru** [asseco-see/api-descriptions#23]
Transaction Codes are extracted from ISO 20022 I suppose. Can you make a reference in the documentation to this document in order to be more clear what is the complete list: https://www.google.ro/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwj1of2ulq3MAhXDAxoKHU6vBIEQFggaMAA&url=https%3A%2F%2Fwww.iso20022.org%2Fdocuments%2FExternal_code_lists%2FBTC_ExternalCodeListDescription_16June09.doc&usg=AFQjCNFE7HVWQqCjj1n9kB04ugXYysS0hw&sig2=neSKc4Ys4b_WKDdUeaa0Fw&bvm=bv.120551593,d.d2s

**Comment by amilos** [comment]
Transaction codes are proprietary codes defined in each core banking system. Example I used in place-holder schema is indeed from ISO 20022 which may lead you to.
If you look at [account-data-classifications.md](api-descriptions/account-data/account-data-classifications.md) you will see the following explanation:

> This classification explains proprietary classification of types of transactions in analytical accounting part of specific core banking system.
>Values in a table below are just a sample placeholder values that will replaced with real ones upon integration with analytical accounting part of core banking system

**Comment by cdubalaru** [comment]
The idea is to have as much as possible classifications independent of implementations in back-end systems. Because for transaction codes there is also a standard in place which is widely used in Europe i believe we should use it.
