### ISSUE TITLE
Register individual method (route) lacks PEP1 and PEP2 field.

### ISSUE THREAD

**Issue by rkrulj** [asseco-see/api-descriptions#29]
Serbian legislation requires collecting of the ''**PEP1**'' and ''**PEP2**'' data onto client registration. Data contract for **party/parties/individuals** route does not contain such fields.

**Comment by amilos** [comment]
APIs deal with three kinds of data - structured, semi-structured (forms) and unstructured (documents). Party API deals with structured data banks keep for parties. Dealing with semi-structured forms for client such as KYC and AML questionnaires is responsibility of **Survey API**. Use method [Capture survey response](https://bankapi.net/docs/internal/survey.html#post-surveys) to record whether party is a foreign official.

**Comment by amilos** [comment]
After discussion and meeting with Saša Mojsić and Lazo Ilijoski we decided to close this issue and stand by suggestion above to use **Survey API** for **PEP** related fields as those cannot be standardized  across banks.
