### ISSUE TITLE
Account Data API - There is not way to attach geolocation info to transaction

### ISSUE THREAD

**Issue by cdubalaru** [asseco-see/api-descriptions#35]

**Comment by amilos** [comment]
To attach picture to transfer you can use [Set transfer's geolocation](https://bankapi.net/docs/internal/payment.html#put-transfers-transfer-id-geolocation) method in Payment API. If you need something different please provide more details.

**Comment by cdubalaru** [comment]
OK but Payments API is relating to payments ordered through digital channels but as end user I want to attach geolocation infor to a transaction even if it wasn't ordered through digital channels. I want to attache geolocation for a card payment and maybe cards processor is not able to attach such information to transaction.
