### ISSUE TITLE
Offer API - new input parameter is needed in GET calculations/transaction-fee

### ISSUE THREAD

**Issue by DPeskir** [asseco-see/api-descriptions#41]
Offer/calculations/transaction-fee:  Input parametar for transaction type is needed. Possible values are listed in transaction-type classification ('balance-transfer', 'cross-border-transfer', 'nonresident-transfer', 'credit-transfer' etc.).
This parameter existed in old definition of method /calculations/service-fee.

**Comment by amilos** [comment]
Use `service-code` field. Service code uniquely identifies service offered to clients such as transfer, currency exchange etc. List of service codes is maintained by Product API - service is listed in product catalogue as a kind of product (kind = `service`).
