### ISSUE TITLE
Loan paid amount and remaining loan obligation are missing in loan arrangement profile

### ISSUE THREAD

**Issue by rkrulj** [asseco-see/api-descriptions#43]
**_**https://bankapi.net/docs/internal/profile.html#get-arrangement-profiles-arrangement-number**_**  should be extended to retrieve information about loan paid amount (but not only principal, interest also has to be included - sum of all paid annuities) and remaining loan obligation (sum of all remaining annuities - interest included).

**Comment by amilos** [comment]
Outstanding balance of a loan that includes all remaining full and partial annuities is available on [Account data API balance inquiry method](https://bankapi.net/docs/internal/account-data.html#get-balances) as `balance-kind=outstanding`.  
Sum of all full or partial repayments will be added in arrangement profile in **Profile API**.
