### ISSUE TITLE
Correspondence API - post instead of get

### ISSUE THREAD

**Issue by markojoksimovic** [asseco-see/api-descriptions#52]
Correspondence YAML Line 171 contains POST instead of GET method.
This is causing problems with generated code.
Documented on enclosed image.

![correspondence](https://cloud.githubusercontent.com/assets/20227220/16761630/4770db84-4821-11e6-9c51-800e8d9b51d5.jpg)

**Comment by amilos** [comment]
Closed with b37675c722e1932f92c51afdf5addbacca2f8163
