### ISSUE TITLE
ProductAPI GET /products/product-code does not return info about the nominal interest rate

### ISSUE THREAD

**Issue by rkrulj** [asseco-see/api-descriptions#55]
ProductAPI GET /products/product-code does not return information about the nominal interest rate, which is necessary for loan (and maybe deposit) products.

**Comment by amilos** [comment]
Terms and conditions for specific product are exposed as sub-resource on another endpoint. Please read the documentation for [Get terms and conditions for specific product](https://bankapi.net/docs/internal/product.html#get-products-product-code-conditions) method.
