### ISSUE TITLE
Information about party that is charged for transfer fee is needed to correctly calculate fee for cross-border transfer

### ISSUE THREAD

**Issue by DPeskir** [asseco-see/api-descriptions#7]
We need to add new field for charge party in request to calculate service fee at following endpoint /calculations/service-fee [Offer API].

**Comment by amilos** [comment]
What do you mean exactly by charge party?

**Comment by DPeskir** [comment]
Who pays the transfer charges, charging instruction  (BEN,OUR,SHA)
